kind: Deployment
apiVersion: apps/v1
metadata:
   name: myapp
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: myapp
   template:
      metadata:
        labels:
          app: myapp
      spec:
       containers:
        - name: myapp
          image: sachitbali/demo-app
          imagePullPolicy: Always
          ports:
          - containerPort: 80