kind: Service                             
apiVersion: v1
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  ports:
    - port: 9099                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: myapp                    
  type: LoadBalancer                   