name: Hprofile Actions
on: workflow_dispatch
env:
    AWS_REGION: ap-southeast-2
    EKS_CLUSTER: demoaapp-cluster
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        
      - name: Maven test
        run: mvn test
        
      - name: Checkstyle
        run: mvn checkstyle:checkstyle 
        
      - name: Set up java 11
        uses: actions/setup-java@v4
        with:
         distribution: 'temurin'
         java-version: '11'
         
  Build-push:
    needs: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWD }}
        
      - name: Build
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: sachitbali/demo-app:latest

  DeploytoEKS:
    needs: Build-push
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy Helm
        uses: bitovi/github-actions-deploy-eks-helm@v1.2.8
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          cluster-name: ${{ env.EKS_CLUSTER }}
          #config-files: .github/values/dev.yaml
          chart-path: demo-counter-app\demoappcharts
          namespace: default
          name: demo-app   
  


