name: Hprofile Actions
on: workflow_dispatch
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        
      - name: Maven test
        run: mvn test
        
      - name: Checkstyle
        run: mvn checkstyle:checkstyle 
        
      - name: Set up java 11
        uses: actions/setup-java@v4
        with:
         distribution: 'temurin'
         java-version: '11'
         
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWD }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: sachitbali/demo-app:V1
